madlibs
adjective1 = input("Type an adjective")
adjective2 = input("Type an adjective")
adjective3 = input("Type an adjective")
adjective4 = input("Type an adjective")
adjective5 = input("Type an adjective")
adjective6 = input("Type an adjective")
adjective7 = input("Type an adjective")
adjective8 = input("Type an adjective")
adjective9 = input("Type an adjective")
adjective10 = input("Type an adjective")
adjective11 = input("Type an adjective")
adjective12 = input("Type an adjective")

noun1 = input("Type a plural noun")
noun2 = input("Type a singular noun")
noun3 = input("Type a plural noun")
noun4 = input("Type a singular noun")
noun5 = input("Type a plural noun")
noun6 = input("Type a singular noun")
noun7 = input("Type a plural noun")
noun8 = input("Type a singular noun")
noun9 = input("Type a plural noun")
noun10 = input("Type a singular noun")
noun11 = input("Type a plural noun")
noun12 = input("Type a singular noun")

verb1 = input("Type a verb (past tense)")
verb2 = input("Type a verb (infinitive, e.g., 'to run')")
verb3 = input("Type a verb (present participle, e.g., '-ing')")
verb4 = input("Type a verb (present tense, e.g., 'runs')")
verb5 = input("Type a verb (past tense)")
verb6 = input("Type a verb (infinitive, e.g., 'to jump')")
verb7 = input("Type a verb (present participle, e.g., '-ing')")
verb8 = input("Type a verb (present tense, e.g., 'jumps')")
verb9 = input("Type a verb (past tense)")
verb10 = input("Type a verb (infinitive, e.g., 'to crawl')")
verb11 = input("Type a verb (present participle, e.g., '-ing')")
verb12 = input("Type a verb (present tense, e.g., 'crawls')")

propernoun1 = input("Type a Proper Noun (person's name)")
propernoun2 = input("Type a Proper Noun (place)")
propernoun3 = input("Type a Proper Noun (fictional character)")
propernoun4 = input("Type a Proper Noun (object or famous artwork)")
propernoun5 = input("Type a Proper Noun (organization, e.g., 'FBI')")
propernoun6 = input("Type a Proper Noun (animal name/species)")
propernoun7 = input("Type a Proper Noun (food brand/item)")

adverb1 = input("Type an adverb")
adverb2 = input("Type an adverb")
adverb3 = input("Type an adverb")

print("The", adjective1, "journey of", propernoun1, "began one", adjective2, "Tuesday afternoon.", propernoun1, "was feeling", adverb1, "motivated after a particularly rough week of", verb3, "practice.", "They had a singular mission: to retrieve the lost", noun2, "of", propernoun3, "from the deepest chamber in", propernoun2, ". The path was fraught with", adjective3, "dangers.", "First, they had to cross the River of", noun1, ". This river was known for its hostile,", adjective4, noun3, "that would", verb4, "at anyone who tried to pass.", propernoun1, ", being quite", adjective5, " (and also slightly", adjective6, "),", verb1, "across the river,", verb5, "as they went.", "On the other side, they encountered a massive", noun6, ". Legend said this", noun6, "had the ability", verb6, "anyone who didn't know the secret password.", "Fortunately, the password was simply 'I love", noun7, ".As they climbed the", adjective7, "slopes of the", noun6, ", they saw", propernoun4, verb7, "towards them.", propernoun4, "!, 'You're back!'", propernoun1, "shouted,", "grabbing their", noun4, ". Propernoun4, ", "they continued,", "'I need your help.", "We must get that", noun2, "before", propernoun5, "gets there first!'", ". Their alliance was sealed with a single,", adjective8, "handshake.", propernoun1, "immediately", verb9, "a plan of action.", "'We need a diversion,'", "they said", adverb2, ". 'Something", adjective9, "that will make the guards forget they\'re supposed", verb2, "'", propernoun4, "nodded", adverb3, ".", noun8, "!, they exclaimed.", "We can use the", adjective10, noun8, "of", propernoun6, "! ", "It\'s so", adjective11, "that anyone who answers it", verb8, "what they were doing.\'","They hiked","for three","more days, past a thicket of", noun9, "that were constantly", verb11, ". Finally, they arrived at the fortress of", propernoun2, ", which was guarded by two incredibly", adjective12, "sentries wearing matching", noun12, ". Quick, distract them!", propernoun1, "ordered.", propernoun4, "pulled out", propernoun7, "from their", noun10, "and began", verb7, "it wildly.", "The guards, momentarily stunned by the sight of", propernoun7, "being", verb7, "so", adverb2, ", stopped paying attention.", propernoun1, "used this window to", verb10, "across the main courtyard, dodging various obstacles, including a rogue", noun4, "that", verb12, "in the middle of the walkway.", "They reached the chamber door, inserted the", noun6, "into the lock, and retrieved the", noun2, "just as", propernoun5, "\'s chief agent arrived,", verb3, "in frustration.", "The mission was a", adjective1, "success!")